/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/

var findTheDifference = function(s, t) {
  let hash = {};
  function helper(string) {
    string.split("").forEach(letter => {
      if(hash[letter] === 1) {
        hash[letter] = 0
      } else {
        hash[letter] = 1
      }
    });
  };
  helper(s);
  helper(t);
  let result;
  Object.entries(hash).forEach(arr => {
    if(arr[1] === 1) {
      result = arr[0];
    }
  })
  return result;
};

findTheDifference('abcd','abcde'); // expect e